apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: location-lookup
  description: Location Lookup
  tags:
    - node
    - api
    - data
spec:
  type: service
  lifecycle: experimental
  owner: team-api
